~/.config/.startup
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/staf/lib"
alias startStaf="/usr/local/staf/bin/STAFProc"
alias filr="cd ~/Documents/filr/filr-qa/trunk"
alias jcli="cd ~/Documents/filr/jenkins_cli"
alias doc="cd ~/Documents"
alias pic="cd ~/Pictures"
alias down="cd ~/Downloads"
alias tcs="cd /home/tanmay/Documents/filr/testcases/Filr"
alias i3="cd /home/tanmay/.config/i3"
alias vim="vim -X"
alias vi="vim -X"
alias fire="/home/tanmay/Documents/personal/fireTV.sh"
alias vpnc="/home/tanmay/Documents/personal/vpn.sh"
alias ll="ls -al"
alias l="ls -al"
alias firetv="~/Documents/personal/fireTV.sh"
alias jenkins="sshpass -p novell ssh -o StrictHostKeyChecking=no tanmay@164.99.118.221"
alias vpnConnect="sshpass -p novell sudo openconnect --protocol=nc --user=corpdom\\btanmay https://apj-remoteaccess.microfocus.net"
alias hyperV="sshpass -p novell ssh root@164.99.117.81 -X"
alias oldJenkins="sshpass -p windows123 ssh -o StrictHostKeyChecking=no jenkins@164.99.118.23"
alias i3git="cd /home/tanmay/Documents/i3"
